version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: os_app
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: os_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
